apiVersion: v1
kind: Pod
metadata:
  name: envpod
  namespace: roboshop
  labels:
    name: krishna
    team: TES
  annotations:
    docke.io: "used for docker reference"
    imageregistry: "https://hub.docker.com/"

spec:
  containers:
    - name: envcontainer
      image: nginx
      envFrom:
        - configMapRef:
            name: configmp