apiVersion: v1
kind: multi-container
metadata:
  name: multi-container
  namespace: roboshop

spec:
  containers:
    - name: container-1
      image: nginx
      ports:
      - containerPort: 80

    - name: container-2
      image: almalinux
      command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600']